name: Version label check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: read

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for version label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: maximum
          count: 1
          labels: "version:major, version:minor, version:patch"
